apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-latency-experiment
  namespace: devops-demo
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - devops-demo
    labelSelectors:
      "app": "api-gateway"
  delay:
    latency: "100ms"
    correlation: "25"
    jitter: "10ms"
  duration: "2m"
  scheduler:
    cron: "@every 10m"
